//
//  PDFExporter.swift
//  SolaPraise
//
//  Renders a detected chord sheet to PDF: title, key, then a chord grid with
//  timestamps, paginated.
//
//  Adapted from PraiseTheLord's PDFExporter, which rendered a WorshipEvent.
//  Same machinery — UIGraphicsPDFRenderer + NSAttributedString, no third-party
//  libraries — pointed at a Session instead.
//
//  CHORDS ONLY, NEVER LYRICS. A chord chart generated by listening is your own
//  work, but worship lyrics are licensed and printing them into a shareable PDF
//  would need your church's CCLI cover. Nothing here emits lyrics.
//

import UIKit
import PDFKit

enum ChordSheetPDF {

    // US Letter at 72 dpi.
    private static let pageSize = CGSize(width: 612, height: 792)
    private static let margin: CGFloat = 54
    private static let columns = 4
    private static let cellHeight: CGFloat = 54

    /// Returns a temporary file URL for ShareLink / UIActivityViewController.
    @MainActor
    static func export(session: Session, semitoneShift: Int = 0, useFlats: Bool = false) -> URL? {
        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(origin: .zero, size: pageSize))
        let safeName = session.title.replacingOccurrences(of: "/", with: "-")
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(safeName.isEmpty ? "ChordSheet" : safeName).pdf")

        let chords = session.chords.map { $0.asChord.transposed(by: semitoneShift) }
        let times = session.chords.map(\.timestamp)

        do {
            try renderer.writePDF(to: url) { ctx in
                ctx.beginPage()
                var y = drawHeader(session: session, semitoneShift: semitoneShift,
                                   useFlats: useFlats, ctx: ctx)

                let usableWidth = pageSize.width - margin * 2
                let cellWidth = usableWidth / CGFloat(columns)

                for (index, chord) in chords.enumerated() {
                    let column = index % columns
                    if column == 0 && index > 0 {
                        y += cellHeight
                        if y + cellHeight > pageSize.height - margin {
                            ctx.beginPage()
                            y = margin
                        }
                    }
                    let rect = CGRect(
                        x: margin + CGFloat(column) * cellWidth,
                        y: y,
                        width: cellWidth,
                        height: cellHeight
                    )
                    draw(chord: chord.symbol(useFlats: useFlats),
                         time: times.indices.contains(index) ? times[index] : 0,
                         in: rect)
                }

                drawFooter(ctx: ctx)
            }
        } catch {
            return nil
        }
        return url
    }

    /// Full lead sheet: sections, chords and lyrics, with the CCLI notice.
    ///
    /// Lyrics are printed only if the user typed them. The CCLI number is
    /// stamped whenever one is set, because that notice is the condition
    /// under which a church licence permits printing lyrics at all.
    @MainActor
    static func exportLeadSheet(song: SavedSong, useFlats: Bool = false) -> URL? {
        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(origin: .zero, size: pageSize))
        let safeName = song.title.replacingOccurrences(of: "/", with: "-")
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(safeName.isEmpty ? "LeadSheet" : safeName).pdf")

        let chords = song.chords
        let bodyWidth = pageSize.width - margin * 2

        do {
            try renderer.writePDF(to: url) { ctx in
                ctx.beginPage()
                var y = margin

                NSAttributedString(
                    string: song.title,
                    attributes: [.font: UIFont.systemFont(ofSize: 24, weight: .bold)]
                ).draw(at: CGPoint(x: margin, y: y))
                y += 32

                var header: [String] = []
                if let key = song.detectedKey { header.append("Key: \(key)") }
                if song.semitoneShift != 0 {
                    header.append("Transposed \(song.semitoneShift > 0 ? "+" : "")\(song.semitoneShift)")
                }
                if !header.isEmpty {
                    NSAttributedString(
                        string: header.joined(separator: "  ·  "),
                        attributes: [
                            .font: UIFont.systemFont(ofSize: 11),
                            .foregroundColor: UIColor.secondaryLabel
                        ]
                    ).draw(at: CGPoint(x: margin, y: y))
                    y += 24
                }

                for section in song.sections {
                    if y > pageSize.height - margin - 90 {
                        ctx.beginPage()
                        y = margin
                    }

                    NSAttributedString(
                        string: "[\(section.label)]",
                        attributes: [.font: UIFont.systemFont(ofSize: 13, weight: .semibold)]
                    ).draw(at: CGPoint(x: margin, y: y))
                    y += 20

                    if chords.indices.contains(section.startIndex) {
                        let upper = min(section.endIndex, chords.count - 1)
                        let line = chords[section.startIndex...upper]
                            .map { $0.asChord.transposed(by: song.semitoneShift).symbol(useFlats: useFlats) }
                            .joined(separator: "   ")
                        let rect = CGRect(x: margin, y: y, width: bodyWidth, height: 200)
                        let attributed = NSAttributedString(
                            string: line,
                            attributes: [
                                .font: UIFont.monospacedSystemFont(ofSize: 12, weight: .semibold),
                                .foregroundColor: UIColor.label
                            ]
                        )
                        attributed.draw(with: rect, options: .usesLineFragmentOrigin, context: nil)
                        y += ceil(attributed.boundingRect(
                            with: CGSize(width: bodyWidth, height: .greatestFiniteMagnitude),
                            options: .usesLineFragmentOrigin, context: nil
                        ).height) + 6
                    }

                    if !section.lyrics.isEmpty {
                        let rect = CGRect(x: margin, y: y, width: bodyWidth, height: 400)
                        let attributed = NSAttributedString(
                            string: section.lyrics,
                            attributes: [.font: UIFont.systemFont(ofSize: 12)]
                        )
                        attributed.draw(with: rect, options: .usesLineFragmentOrigin, context: nil)
                        y += ceil(attributed.boundingRect(
                            with: CGSize(width: bodyWidth, height: .greatestFiniteMagnitude),
                            options: .usesLineFragmentOrigin, context: nil
                        ).height) + 8
                    }
                    y += 10
                }

                var notice = "Detected with SolaPraise"
                if let ccli = song.ccliNumber, !ccli.isEmpty {
                    notice = "CCLI #\(ccli)  ·  " + notice
                } else if song.hasLyrics {
                    notice = "가사 사용 시 CCLI 라이선스 필요  ·  " + notice
                }
                NSAttributedString(
                    string: notice,
                    attributes: [
                        .font: UIFont.systemFont(ofSize: 8),
                        .foregroundColor: UIColor.tertiaryLabel
                    ]
                ).draw(at: CGPoint(x: margin, y: pageSize.height - margin + 12))
            }
        } catch {
            return nil
        }
        return url
    }

    // MARK: - Pieces

    private static func drawHeader(session: Session, semitoneShift: Int,
                                   useFlats: Bool, ctx: UIGraphicsPDFRendererContext) -> CGFloat {
        let title = NSAttributedString(
            string: session.title + "\n",
            attributes: [.font: UIFont.systemFont(ofSize: 26, weight: .bold)]
        )
        title.draw(at: CGPoint(x: margin, y: margin))

        var subtitleParts: [String] = []
        if let key = session.detectedKey { subtitleParts.append("Key: \(key)") }
        if semitoneShift != 0 {
            subtitleParts.append("Transposed \(semitoneShift > 0 ? "+" : "")\(semitoneShift)")
        }
        subtitleParts.append(session.createdAt.formatted(date: .abbreviated, time: .shortened))

        let subtitle = NSAttributedString(
            string: subtitleParts.joined(separator: "  ·  "),
            attributes: [
                .font: UIFont.systemFont(ofSize: 11, weight: .regular),
                .foregroundColor: UIColor.secondaryLabel
            ]
        )
        subtitle.draw(at: CGPoint(x: margin, y: margin + 34))

        return margin + 68
    }

    private static func draw(chord symbol: String, time: TimeInterval, in rect: CGRect) {
        let box = rect.insetBy(dx: 4, dy: 4)
        let path = UIBezierPath(roundedRect: box, cornerRadius: 6)
        UIColor.systemGray6.setFill()
        path.fill()

        let chordText = NSAttributedString(
            string: symbol,
            attributes: [.font: UIFont.systemFont(ofSize: 18, weight: .semibold)]
        )
        let chordSize = chordText.size()
        chordText.draw(at: CGPoint(
            x: box.midX - chordSize.width / 2,
            y: box.minY + 8
        ))

        let minutes = Int(time) / 60, seconds = Int(time) % 60
        let timeText = NSAttributedString(
            string: String(format: "%d:%02d", minutes, seconds),
            attributes: [
                .font: UIFont.monospacedDigitSystemFont(ofSize: 9, weight: .regular),
                .foregroundColor: UIColor.secondaryLabel
            ]
        )
        let timeSize = timeText.size()
        timeText.draw(at: CGPoint(
            x: box.midX - timeSize.width / 2,
            y: box.maxY - timeSize.height - 6
        ))
    }

    private static func drawFooter(ctx: UIGraphicsPDFRendererContext) {
        let text = NSAttributedString(
            string: "Detected with SolaPraise · chords only",
            attributes: [
                .font: UIFont.systemFont(ofSize: 8),
                .foregroundColor: UIColor.tertiaryLabel
            ]
        )
        text.draw(at: CGPoint(x: margin, y: pageSize.height - margin + 12))
    }
}
